name: Build Project and push JavaScript to dedicated branch
on:
    push:
        branches:
            # Replace this with `dev` if and when it gets merged
            - typescript
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              # Ignore postinstall because we don't need to run test in this build
              run: yarn --ignore-scripts
            - name: Build project
              env:
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
              # `exit 0` temporarily so it ignores all the many many many build errors
              # Also send error count to WebHook
              run: |
                  yarn build --pretty > typescript_build.log || exit 0
                  echo $WEBHOOK_URL
                  echo $COMMIT_MESSAGE
                  echo $GITHUB_SERVER_URL
                  echo $GITHUB_REPOSITORY
                  echo $GITHUB_RUN_ID
                  node .github/prettify_log.mjs
            - name: Make sure we don't push source files
              run: |
                  sed -i 's/^js//' .gitignore
                  sed -i 's/^css//' .gitignore
                  rm -rf src
                  rm -rf styles
                  rm typescript_build.log
            - name: Switch to JavaScript branch
              run: |
                  git fetch
                  git reset --soft origin/javascript
                  git switch javascript
            - name: Commit all changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Actions"
                  git add .
                  git commit -m "Automatic build of commit \`$GITHUB_SHA\`" -a
                  git push
